mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from .views import landing_page, about_page, contact_page, HomePageView, FamilyPageView


urlpatterns = [
    path('', landing_page, name='home'),
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('accounts.passwords.urls', namespace='password')),
    path('account/', RedirectView.as_view(url='/accounts')),
    path('welcome/', HomePageView.as_view(), name='welcome'),
    path('welcome/family/', FamilyPageView.as_view(), name='family'),
    path('gallery/', include('gallery.urls', namespace='gallery-custom')),
    path('photologue/', include('gallery.urls')),
    path('photologue/', include('photologue.urls', namespace='photologue')),
    path('settings/', RedirectView.as_view(url='/accounts')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wedding/urls.py
from django.urls import path

from .views import WeddingHomeView, EventRsvpView, WeddingGalleryListView, WeddingGalleryDetailView

app_name = 'wedding'

urlpatterns = [

	path('', WeddingHomeView.as_view(), name='home'),
	path('rsvp/', EventRsvpView.as_view(), name='rsvp'),
	path('gallery/', WeddingGalleryListView.as_view(), name='list-gallery'),
	path('gallery/detail', WeddingGalleryDetailView.as_view(), name='detail-gallery'),

]

wedding/models.py
from django.db import models
from django.conf import settings

User = settings.AUTH_USER_MODEL

EVENT_CHOICES = (
	('Church Service', 'Church Service'),
	('Bachelor Party', 'Bachelor Party'),
    ('Bachelorette Party', 'Bachelorette Party'),
    ('Bridal Shower', 'Bridal Shower'),
    ('Reception', 'Reception'),
)

GUEST_CHOICES = (
	('00', '00'),
	('01', '01'),
    ('02', '02'),
    ('03', '03'),
    ('04', '04'),
    ('05', '05'),
)

class EventRsvp(models.Model):
	User 		= models.ForeignKey(User, on_delete=models.CASCADE)
	event 		= models.CharField(max_length=20, choices=EVENT_CHOICES, default='Church Service')
	guest 		= models.CharField(max_length=2, choices=GUEST_CHOICES, default='00')
	timestamp 	= models.DateTimeField(auto_now_add=True)

	class Meta:
	    verbose_name = "Event Rsvp"
	    verbose_name_plural = "Events Rsvp"

	def __str__(self):
	    return self.user.full_name


class WeddingPicture(models.Model):

    class Meta:
        verbose_name = "Wedding Picture"
        verbose_name_plural = "Wedding Pictures"

    def __str__(self):
        pass

wedding/forms.py
from django.forms import ModelForm
from django.conf import settings

User = settings.AUTH_USER_MODEL

from .models import EventRsvp


class EventRsvpForm(ModelForm):
    class Meta:
        model = EventRsvp
        fields = ['event', 'guest']

wedding/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, CreateView, ListView, DetailView
from django.shortcuts import render

from .forms import EventRsvpForm

from .models import WeddingPicture

# Create your views here.


class WeddingHomeView(TemplateView):
     template_name = 'wedding/wedding.html'
    # def get_object(self):
    #     return self.request.user

class EventRsvpView(CreateView):
	form_class = EventRsvpForm
	template_name = 'wedding/rsvp.html'

class WeddingGalleryListView(ListView):
	model = WeddingPicture
	template_name='wedding/gallery-list.html'

class WeddingGalleryDetailView(DetailView):
	pass

wedding/templates/wedding/snippets/footer.html
<!-- Footer -->
{% load static %}
<footer class="footerhead">
	<div class="container">
		<div class="row">
			<div class="col my-auto">
				<div class="footer-content mx-auto">
					<h1 class="mb-1">David <i class="fa fa-heart"></i> Allen<br><img src=" {% static 'wedding/images/heading.png' %} " class="img-fluid" alt="footer-heading"></h1>
					<h2 class="mb-5">Forever And Always Our Love<br>Thank You</h2>
				</div>
			</div>
		</div>
	</div>
</footer>
<!--div class="copyright">
	<div class="row w-100">
			<div class="col mx-auto">
				
					<p>
						&copy;
						{% now 'Y' %},
						{{request.get_host}} | All rights reserved <br>
						<a href="#">Terms of Use | Privacy Policy</a>
					</p>
				
			</div>
		</div>
</div-->

wedding/templates/wedding/snippets/js.html
{% load static %}

<!-- Plugin JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

<!-- Custom scripts for this template -->
<script type="text/javascript" src=" {% static "wedding/js/wedding-new-age.min.js" %} "></script>

wedding/templates/wedding/snippets/navbar.html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="#page-top"></a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    Menu
    <i class="fa fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        {% url 'home' as home_url %}
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{{home_url}}">Home</a>
        </li>
        {% url 'wedding:home' as wedding_url %}
        {% if not request.path == wedding_url %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{{wedding_url}}">Wedding</a>
          </li>
        {% endif %}
        {% if request.path == wedding_url %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#invitation-features">Rsvp</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#gift-features">Gifts</a>
          </li>
        {% endif %}
        {% url 'wedding:list-gallery' as gallery_url %}
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{{gallery_url}}">Gallery</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<header class="masthead">
  <div class="container h-100">
    <div class="row h-100">
      <div class="col my-auto">
        <div class="header-content mx-auto">
          <h1 class="mb-5">David & Allen</h1>
        </div>
      </div>
    </div>
  </div>
</header>