accounts/passwords/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns  = [
    path('password/change/',
            auth_views.PasswordChangeView.as_view(),
            name='password_change'),
    path('password/change/done/',
            auth_views.PasswordChangeDoneView.as_view(),
            name='password_change_done'),
    path('password/reset/',
            auth_views.PasswordResetView.as_view(),
            name='password_reset'),
    path('password/reset/done/',
            auth_views.PasswordResetDoneView.as_view(),
            name='password_reset_done'),
    path('password/reset/<uidb64>/<token>/',
            auth_views.PasswordResetConfirmView.as_view(),
            name='password_reset_confirm'),

    path('password/reset/complete/',
            auth_views.PasswordResetCompleteView.as_view(),
            name='password_reset_complete'),
]

# accounts/login/ [name='login']
# accounts/logout/ [name='logout']
# accounts/password_change/ [name='password_change']
# accounts/password_change/done/ [name='password_change_done']
# accounts/password_reset/ [name='password_reset']
# accounts/password_reset/done/ [name='password_reset_done']
# accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/reset/done/ [name='password_reset_complete']

accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import LogoutView

from .views import (
                LoginView,
                RegisterView,
                GuestRegisterView,
                AccountHomeView,
                AccountEmailActivateView,
                UserDetailUpdateView,
            )

app_name = 'accounts'

urlpatterns = [
    path('', AccountHomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register/guest/', GuestRegisterView.as_view(), name='guest_register'),
    #re_path(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivateView.as_view(), name='email-activate'),
    path('email/confirm/<key>/', AccountEmailActivateView.as_view(), name='email-activate'),
    path('email/resend-activation/', AccountEmailActivateView.as_view(), name='resend-activation'),
    path('details/', UserDetailUpdateView.as_view(), name='user-update'),
    
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from .views import landing_page, about_page, contact_page, HomePageView, FamilyPageView


urlpatterns = [
    path('', landing_page, name='home'),
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('accounts.passwords.urls', namespace='password')),
    path('account/', RedirectView.as_view(url='/accounts')),
    path('welcome/', HomePageView.as_view(), name='welcome'),
    path('welcome/family/', FamilyPageView.as_view(), name='family'),
    path('gallery/', include('gallery.urls', namespace='gallery-custom')),
    path('photologue/', include('gallery.urls')),
    path('photologue/', include('photologue.urls', namespace='photologue')),
    path('settings/', RedirectView.as_view(url='/accounts')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from django.urls import reverse
from django.utils.safestring import mark_safe

from .models import EmailActivation, GuestEmail

User = get_user_model()

class ReactivateEmailForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = EmailActivation.objects.email_exists(email)
        if not qs.exists():
            register_link = reverse("accounts:register")
            msg = """This email does not exists, would you like to <a href="{link}">register</a>?
            """.format(link=register_link)
            raise forms.ValidationError(mark_safe(msg))
        return email


class UserAdminCreationForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required
    fields, plus a repeated password.
    """
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('full_name', 'email',)

    def clean_password2(self):
        """
        Check that the two password entries match
        """
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        """
        Save the provided password in hashed format
        """
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserDetailChangeForm(forms.ModelForm):
    full_name = forms.CharField(label='Name', required=False, widget=forms.TextInput(attrs={"class": 'form-control'}))

    class Meta:
        model = User
        fields = ['full_name']


class UserAdminChangeForm(forms.ModelForm):
    """
    A form for updating users. Includes all the fields on the user, 
    but replaces the password field with admin's password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('full_name', 'email', 'password', 'is_active', 'admin')

    def clean_password(self):
        """
        Regardless of what the user provides, return the initial value. 
        This is done here, rather than on the field, because the field does not have access to the initial value
        """
        return self.initial["password"]


class GuestForm(forms.ModelForm):
    #email    = forms.EmailField()
    class Meta:
        model = GuestEmail
        fields = [
            'email'
        ]

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(GuestForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        """
        Save the provided password in hashed format
        """
        obj = super(GuestForm, self).save(commit=False)
        if commit:
            obj.save()
            request = self.request
            request.session['guest_email_id'] = obj.id
        return obj


class LoginForm(forms.Form):
    email    = forms.EmailField(
            widget=forms.EmailInput(
                    attrs={
                        "class": "form-control", 
                        "placeholder": "Your Email"
                    }
                    )
            )
    password = forms.CharField(widget=forms.PasswordInput(
                    attrs={
                        "class": "form-control",
                        "placeholder": "Enter Password"
                    }
                )
            )

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean(self):
        request = self.request
        data = self.cleaned_data
        email  = data.get("email")
        password  = data.get("password")
        qs = User.objects.filter(email=email)
        if qs.exists():
            """
            User email is registered, check if is active
            """
            not_active = qs.filter(is_active=False)
            if not_active.exists():
                """
                Not active, check email activation
                """
                link = reverse("accounts:resend-activation")
                reconfirm_msg = """Go to <a href='{resend_link}'>
                resend confirmation email</a>.
                """.format(resend_link = link)
                confirm_email = EmailActivation.objects.filter(email=email)
                is_confirmable = confirm_email.confirmable().exists()
                if is_confirmable:
                    msg1 = "Please check your email to confirm your account or " + reconfirm_msg.lower()
                    raise forms.ValidationError(mark_safe(msg1))
                email_confirm_exists = EmailActivation.objects.email_exists(email).exists()
                if email_confirm_exists:
                    msg2 = "Email not confirmed. " + reconfirm_msg
                    raise forms.ValidationError(mark_safe(msg2))
                if not is_confirmable and not email_confirm_exists:
                    raise forms.ValidationError("This user is inactive.")
        user = authenticate(request, username=email, password=password)
        if user is None:
            raise forms.ValidationError("Invalid credentials")
        login(request, user)
        self.user = user
        return data


class RegisterForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required fields, plus a confirm password.
    """
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('full_name', 'email',)

    def clean_password2(self):
        """
        Check that the two password entries match
        """
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        """
        Save the provided password in hashed format
        """
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = False
        """
        send confirmation email via signals
        """
        if commit:
            user.save()
        return user

accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from mysite.mixins import NextUrlMixin, RequestFormAttachMixin
from django.contrib import messages
from django.urls import reverse
from django.views.generic import CreateView, FormView, DetailView, View, UpdateView
from django.views.generic.edit import FormMixin
from django.shortcuts import render, redirect
from django.utils.safestring import mark_safe


from .forms import LoginForm, RegisterForm, GuestForm, ReactivateEmailForm, UserDetailChangeForm
from .models import EmailActivation

from .signals import user_logged_in


class AccountHomeView(LoginRequiredMixin, DetailView):
    template_name = 'accounts/home.html'
    def get_object(self):
        return self.request.user

class AccountEmailActivateView(FormMixin, View):
    success_url = '/accounts/login/'
    form_class = ReactivateEmailForm
    key = None
    def get(self, request, key=None, *args, **kwargs):
        self.key = key
        if key is not None:
            qs = EmailActivation.objects.filter(key__iexact=key)
            confirm_qs = qs.confirmable()
            if confirm_qs.count() == 1:
                obj = confirm_qs.first()
                obj.activate()
                messages.success(request, "Your email has been confirmed. Please login.")
                return redirect("accounts:login")
            else:
                activated_qs = qs.filter(activated=True)
                if activated_qs.exists():
                    reset_link = reverse("password_reset")
                    msg = """Your email has already been confirmed
                    Do you need to <a href="{link}">reset your password</a>?
                    """.format(link=reset_link)
                    messages.success(request, mark_safe(msg))
                    return redirect("accounts:login")
        context = {'form': self.get_form(),'key': key}
        return render(request, 'registration/activation-error.html', context)


    def post(self, request, *args, **kwargs):
        # create form to receive an email
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        msg = """Activation link sent, please check your email."""
        request = self.request
        messages.success(request, msg)
        email = form.cleaned_data.get("email")
        obj = EmailActivation.objects.email_exists(email).first()
        user = obj.user
        new_activation = EmailActivation.objects.create(user=user, email=email)
        new_activation.send_activation()
        return super(AccountEmailActivateView, self).form_valid(form)

    def form_invalid(self, form):
        context = {'form': form, "key": self.key }
        return render(self.request, 'registration/activation-error.html', context)


class GuestRegisterView(NextUrlMixin, RequestFormAttachMixin, CreateView):
    form_class = GuestForm
    default_next = '/accounts/register/'

    def get_success_url(self):
        return self.get_next_url()

    def form_invalid(self, form):
        return redirect(self.default_next)


class LoginView(NextUrlMixin, RequestFormAttachMixin, FormView):
    form_class = LoginForm
    success_url = '/'
    template_name = 'accounts/login-register.html'

    def form_valid(self, form):
        next_path = self.get_next_url()
        return redirect(next_path)


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'accounts/login-register.html'
    success_url = '/accounts/login/'


class UserDetailUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserDetailChangeForm
    template_name = 'accounts/detail-update-view.html'

    def get_object(self):
        return self.request.user

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Change Your Account Details'
        return context

    def get_success_url(self):
        return reverse("accounts:home")

accounts/templates/accounts/detail-update-view.html
{% extends "base.html" %}
{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form.as_p }}
  <label for='email'>Email</label>
  <input type='text' id='email' class='form-control disabled' value='{{ request.user.email }}' disabled="disabled" /><span class='help-text'>Cannot change email</span><br/>
  <button type='submit' class='btn btn-default my-3'>Save</button>
  <a href='{% url "password_change" %}'>Change Password</a>
</form>
</div>
{% endblock %}

accounts/templates/accounts/home.html
{% extends "base/base.html" %}

{% block content %}
<div class='row'>
<div class='col-12'>
<h1>Account</h1>
<hr/>
</div>
<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Support</h4>
            <div class='list-group'>
                <a class='list-group-item' href='{% url "about" %}'>About</a>
                <a class='list-group-item' href='{% url "contact" %}'>Contact</a>
            </div>
      </div>
    </div>
</div>



<div class='col-12 col-md-3 my-3' id='billing'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Billing</h4>
            <div class='list-group'>
                <a class='list-group-item' href='{% url "orders:list" %}'>Orders</a>
                <a class='list-group-item' href='{% url "billing-payment-method" %}'>Payment Methods</a>
                <a class='list-group-item' href='{% url "addresses" %}'>Addresses</a>
                
                
            </div>
      </div>
    </div>
</div>


<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Account Details</h4> 
            <div class='list-group'>
                <a class='list-group-item' href='{% url "accounts:user-update" %}'>Update Details</a>
                <a class='list-group-item' href='{% url "password_change" %}'>Change Password</a>
                <a class='list-group-item' href='{% url "library" %}'>Library</a>
                
            </div>

      </div>
    </div>
</div>


<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Preferences</h4> 
            <div class='list-group'>
                <a class='list-group-item' href='{% url "marketing-pref" %}'>Email Marketing</a>
                
            </div>

      </div>
    </div>
</div>


<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">History</h4> 
              <div class='list-group'>
                <a class='list-group-item' href='{% url "accounts:user-product-history" %}'>Products</a>
            </div>
      </div>
    </div>
</div>


</div>


{% endblock %}

accounts/templates/accounts/login-register.html
		{% extends 'base_2.html' %}{% url 'accounts:login' as login_url %}{% url 'accounts:register' as register_url %}{% load i18n %}{% load crispy_forms_tags %}{% block extrahead %}{% load  static %}
		<!-- Signin CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/signin.css' %}">{% endblock extrahead %}{% block page_title %}{% if request.path == login_url  %}{% blocktrans with page_title|default:"sign-In"|title as page_title %}{{page_title}}{% endblocktrans %}{% elif request.path == register_url %}{% blocktrans with page_title|default:"sign-Up"|title as page_title %}{{page_title}}{% endblocktrans %}{% endif %}{% endblock page_title %}{% block content %}{% url 'accounts:login' as login_url %}{% url 'accounts:register' as register_url %}
		<section class="flexin-block-features" id="flexin-block-features">
			<div class="container">
				<div class="row">
					<div class="col-lg-4 offset-lg-8">
						<div class="card card-top bg-light">
							<div class="card-body">
								<div class="card-title card-title-top">
									<h3 data-title="{% if request.path == login_url  %}{% blocktrans with login_title|default:'login'|upper as login_title %}{{login_title}}{% endblocktrans %}{% else %}{% blocktrans with register_title|default:'please register'|upper as register_title %}{{register_title}}{% endblocktrans %}{% endif %}"></h3>
								</div>
								<form method="POST">{% csrf_token %}{{ form|crispy }}
									<button type='submit' class='btn btn-outline-warning'>{% if request.path == login_url %}{% blocktrans with submit_btn|default:"sign in"|title as submit_btn %}{{submit_btn}}{% endblocktrans %}{% elif request.path == register_url %}{% blocktrans with submit_btn|default:"register"|title as submit_btn %}{{submit_btn}}{% endblocktrans %}{% endif %}</button>
								</form>{% if request.path == login_url  %}
								<p>{% trans "Forgot Password" %}? <a href=" {% url 'password:password_reset' %} " class="card-link">{% trans "Reset" %}</a>!</p>
								<p>{% trans "Not Member" %}? <a href=" {{register_url}} " class="card-link">{% trans "Register" %}</a>!</p>{% elif request.path == register_url  %}
								<p>{% trans "Already a Member" %}? <a href=" {{login_url}} " class="card-link">{% trans "Sign In" %}</a>!</p>{% endif %}
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>{{block.super}}{% endblock %}



	

accounts/templates/accounts/login.html
{% extends "base/base_2.html" %}

	{% load i18n %}

	{% load crispy_forms_tags %}

	{% block extrahead %}
		{% load  static %}
		<!-- Cover CSS -->
		<link rel="stylesheet" type="text/css" href=" {% static "css/signin.css" %} "> 
	{% endblock extrahead %}

	{% block page_title %}{% trans "Sign In" %}{% endblock page_title %} 

	{% block content %}
	<div class="container">
		<div class="row mt-5">
  			<div class="col-lg-6 offset-lg-3">
  				<div class="card mx-auto">
  					<div class="card-body">
					    <h5 class="card-title font-weight-normal text-center">{% trans "Sign In" %}</h5>
					    <h6 class="card-subtitle mb-2 text-muted text-center"> {% trans "Welcome to Our Site" %} </h6>
					    <form method='POST'> 
					    	{% csrf_token %}
							{{ form|crispy }}
							<button type='submit' class='btn btn-outline-primary btn-block mb-3'> {% trans "Sign In" %} </button>
						</form>
			    		<p>{% trans "Forgot password" %}? <a href=" {% url 'password:password_reset' %} " class="card-link">{% trans "Reset" %}</a>!</p>
						<p>{% trans "Not member" %}? <a href=" {% url 'accounts:register' %} " class="card-link">{% trans "Register" %}</a>!</p>
  					</div>
				</div>
  			</div>
		</div>
	</div>	
	{% endblock %}



	

accounts/templates/accounts/register.html
{% extends "base/base_2.html" %}

	{% load i18n %}

	{% load crispy_forms_tags %}

	{% block extrahead %}
		{% load  static %}
		<!-- Cover CSS -->
		<link rel="stylesheet" type="text/css" href=" {% static "css/signin.css" %} "> 
	{% endblock extrahead %}

	{% block page_title %}{% trans "Register" %}{% endblock page_title %} 

	{% block content %}
	<div class="container">
		<div class="row mt-5">
  			<div class="col-lg-6 offset-lg-3">
  				<div class="card mx-auto">
  					<div class="card-body">
					    <h5 class="card-title font-weight-normal text-center">{% trans "Please Register" %}</h5>
					    <h6 class="card-subtitle mb-2 text-muted text-center"> {% trans "Welcome to Our Site" %} </h6>
					    <form method='POST'> 
					    	{% csrf_token %}
							{{ form|crispy }}
							<button type='submit' class='btn btn-outline-primary btn-block mb-3'> {% trans "Register" %} </button>
						</form>
						<p>{% trans "Already a member" %}? <a href=" {% url 'accounts:login' %} " class="card-link">{% trans "Sign In" %}</a>!</p>
  					</div>
				</div>
  			</div>
		</div>
	</div>	
	{% endblock %}