gallery/urls.py
from django.urls import path
from photologue.views import GalleryListView, GalleryDetailView, PhotoListView, PhotoDetailView

app_name = "gallery"

urlpatterns = [
	path('', GalleryListView.as_view(), name='gallery-list'),
	path('<slug:slug>/', GalleryDetailView.as_view(), name='gallery-detail'),
	path('photolist/', PhotoListView.as_view(), name='gallery-photo-list'),
	path('photo/<slug:slug>/', PhotoDetailView.as_view(), name='gallery-photo-detail'),

]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from .views import landing_page, about_page, contact_page, HomePageView, FamilyPageView


urlpatterns = [
    path('', landing_page, name='home'),
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('accounts.passwords.urls', namespace='password')),
    path('account/', RedirectView.as_view(url='/accounts')),
    path('welcome/', HomePageView.as_view(), name='welcome'),
    path('welcome/family/', FamilyPageView.as_view(), name='family'),
    path('gallery/', include('gallery.urls', namespace='gallery-custom')),
    path('photologue/', include('gallery.urls')),
    path('photologue/', include('photologue.urls', namespace='photologue')),
    path('settings/', RedirectView.as_view(url='/accounts')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/templates/photologue/gallery_detail.html
		{% extends "photologue/root.html" %}
	    {% load i18n %}
	    {% block extrahead %}{% load  static %}<!-- Custom fonts for this template -->
	    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
	    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">{% endblock extrahead %}
	    {% block page_title %}{% blocktrans with gallery.title|default:"photo galleries"|title as gallery.title %}{{gallery.title}}{% endblocktrans %}{% endblock page_title %}{% block content %}
	    <h1 class="site-heading text-center text-white d-none d-lg-block">
	        <span class="site-heading-upper text-muted mb-3 d-none">{% blocktrans with gallery.title|default:"our gallery"|add:" gallery"|upper as gallery.title %}{{gallery.title}}{% endblocktrans %}</span>
	        <span class="site-heading-lower text-muted">{% blocktrans with gallery.title|default:"photo gallery"|add:"  gallery"|upper as gallery.title %}{{gallery.title}}{% endblocktrans %}</span>
	    </h1>
	    <section class="gallery-select-feature" id="gallery-select-feature">
	    	<div class="container">
	    		<div class="row"> {% if gallery.description %}
	    			<div class="card mb-3 d-none d-lg-block">
	    				<div class="row">
	    					<div class="col-lg-4">{% for photo in gallery.sample  %}{% if forloop.counter0 == 0 %}
	                        <img class="card-img-top img-fluid h-100" src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}">{% endif %}{% endfor %}</div>
	    					<div class="col-lg-8">
	    						<div class="card-body">
	    							<h5 class="card-title"> {{gallery.title}} </h5>
	    							<p class="card-text">{{ gallery.description|safe }}</p>
	    							<!--Link or btn for slideshow-->
	    							<a href="#" class="card-link "></a>
	    						</div>
	    					</div>
	    				</div>
	    			</div>{% endif %}{% for photo in gallery.public %}
		    		<div class="col-lg-3 col-md-4 col-sm-6">
		          		<a href="{% url 'gallery:gallery-photo-detail' photo.slug %}" class="d-block mb-4 w-100">
		            		<img class="img-fluid" src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}">
		          		</a>
		    		</div>{% endfor %}
		    		<div class="col-12 text-center mb-4">
		    			<a href="{% url 'gallery:gallery-list' %}" class="btn btn-outline-secondary">{% trans "View All Galleries" %}</a>
		    		</div>
	    		</div>
	    	</div>
	    </section>
	    {{block.super}}{% endblock content %}

gallery/templates/photologue/gallery_list.html
        {% extends "photologue/root.html" %}
        {% load i18n %}
        {% block extrahead %}{% load  static %}<!-- Custom fonts for this template -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">{% endblock extrahead %}
        {% block page_title %}{% blocktrans with page_title|default:"photo galleries"|title as page_title %}{{page_title}}{% endblocktrans %}{% endblock page_title %}{% block content %}
        <h1 class="site-heading text-center text-white d-none d-lg-block">
            <span class="site-heading-upper text-warning mb-3">{% blocktrans with site_heading_upper|default:"david & allen mason family"|upper as site_heading_upper %}{{site_heading_upper}}{% endblocktrans %}</span>
            <span class="site-heading-lower text-muted">{% blocktrans with site_heading_lower|default:"photo galleries"|upper as site_heading_lower %}{{site_heading_lower}}{% endblocktrans %}</span>
        </h1>
        <section class="gallery-feature family-gallery" id="gallery-feature">
            <div class="container">
                <div class="row">{% if object_list %}{% for gallery  in object_list  %}
                    <div class="col-sm-6 col-lg-4 gallery-item">
                        <div class="card h-100">{% for photo in gallery.sample  %}{% if forloop.counter0 == 0 %}
                            <img class="card-img-top img-fluid" src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}">{% endif %}{% endfor %}
                            <div class="card-body d-flex flex-column">
                                <h4 class="card-title">{{ gallery.title }}</h4>
                                <p class="text-muted published mb-0"><small>{% trans "Published" %} {{ gallery.date_added }}</small></p>{% if gallery.description %}
                                <p class="card-text">{{ gallery.description|truncatewords:20|safe }}</p>{% endif %}
                                <!--a href="{{ gallery.get_absolute_url }}" class="btn btn-outline-secondary mt-auto">{% trans "View Gallery" %}</a-->
                                <a href="{% url 'gallery:gallery-detail' gallery.slug %}" class="btn btn-outline-secondary mt-auto">{% trans "View Gallery" %}</a>
                            </div>
                            <!--class="card-footer text-center">
                                <p class="text-muted published mb-0"><small>{% trans "Published" %} {{ gallery.date_added }}</small></p>
                            </div-->
                        </div>
                    </div>{% endfor %}{% else %}
                    <div class="col-lg gallery-item-none">
                        <div class="card">
                            <div class="card-body">
                                <h1>{% trans "No galleries were found" %}</h1>
                            </div>
                        </div>
                    </div>{% endif %}
                </div>
            </div>
        </section>{{block.super}}{% endblock content %}

gallery/templates/photologue/photo_detail.html
        {% extends "photologue/root.html" %}
        {% load i18n %}
        {% block extrahead %}{% load  static %}<!-- Custom fonts for this template -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">{% endblock extrahead %}
        {% block page_title %}{% blocktrans with object.title|default:"photo galleries"|title as object.title %}{{object.title}}{% endblocktrans %}{% endblock page_title %}{% block content %}
        <h1 class="site-heading text-center text-white d-none d-lg-block">
            <span class="site-heading-upper text-muted mb-3 d-none">{% blocktrans with object.title|default:"our gallery"|add:" gallery"|upper as object.title %}{{object.title}}{% endblocktrans %}</span>
            <span class="site-heading-lower text-muted">{% blocktrans with object.title|default:"photo gallery"|upper as object.title %}{{object.title}}{% endblocktrans %}</span>
        </h1>
        <section class="photo-detail-feature" id="photo-detail-feature">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="card photo-detail">
                            <img src="{{ object.get_display_url }}" alt="{{ object.title }}" class="card-img-top w-100">
                            <div class="card-body">
                                <h3 class="card-title">{% blocktrans with object.title|title as object.title %}{{object.title}}{% endblocktrans %}</h3>
                                <p class="card-text">{{ object.caption|safe }}</p>
                                <p class="text-muted"><small>{% trans "Published" %} {{ object.date_added }}</small></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {{block.super}}{% endblock %}

gallery/templates/photologue/photo_list.html
        {% extends "photologue/root.html" %}
        {% load i18n %}
        {% block extrahead %}{% load  static %}<!-- Custom fonts for this template -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">{% endblock extrahead %}
        {% block page_title %}{% blocktrans with object.title|default:"all our photos"|title as object.title %}{{object.title}}{% endblocktrans %}{% endblock page_title %}{% block content %}
        <h1 class="site-heading text-center text-white d-none d-lg-block">
            <span class="site-heading-upper text-muted mb-3 d-none">{% blocktrans with object.title|default:"our gallery"|add:" gallery"|upper as object.title %}{{object.title}}{% endblocktrans %}</span>
            <span class="site-heading-lower text-muted">{% blocktrans with object.title|default:"all our photos"|upper as object.title %}{{object.title}}{% endblocktrans %}</span>
        </h1>
        <section class="photo-list-feature" id="photo-list-feature">
        	<div class="container">
        		<div class="row"> {% if object_list %} {% for photo in object_list %}
        			<div class="col-lg-3 col-md-4 col-sm-6">
		          		<a href="{% url 'gallery:gallery-photo-detail' photo.slug %}" class="d-block mb-4 w-100">
		            		<img class="img-fluid" src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}">
		          		</a>
		    		</div>{% endfor %}{% else %}
		    		<div class="col-md offset-md-3">
		    			<div class="card mx-auto bg-dark text-white">
		    				<div class="card-body text-center">
		    					<h3 class="card-title">{% blocktrans with no_photo_title|default: "sorry!!"|title as no_photo_title %}{{no_photo_title}}{% endblocktrans %}</h3>
		    					<p class="card-text">{% blocktrans with no_photo_message|default: "no photo images have been uploaded yet, ceck again when you visit our site"|upper as no_photo_message %}{{no_photo_message}}{% endblocktrans %}</p>
		    				</div>
		    			</div>
		    		</div>{% endif %}{% include "photologue/snippets/paginator.html" %}
        		</div>
        	</div>
        </section>{{block.super}}{% endblock %}